package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

// originally copied from:
// https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
//

func loadMimeFile(filename string) map[string]string {
	out := make(map[string]string)
	f, err := os.Open(filename)
	if err != nil {
		panic(err)
	}
	// prevent errcheck warning
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) <= 1 || fields[0][0] == '#' {
			continue
		}
		mimeType := fields[0]
		for _, ext := range fields[1:] {
			if ext[0] == '#' {
				break
			}
			out["."+ext] = mimeType
		}
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}

	return out
}

func main() {
	out := loadMimeFile("mime.type")
	fmt.Printf("package httpmime\n")
	fmt.Printf("\n")
	fmt.Printf("// Code generated by github.com/client9/httpmime DO NOT EDIT.\n")
	fmt.Printf("// Source: https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types\n")
	fmt.Printf("\n")
	fmt.Printf("var mimeTypes = map[string]string {\n")

	keys := make([]string, 0, len(out))
	for k := range out {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		fmt.Printf("\t%q: %q,\n", k, out[k])
	}
	fmt.Printf("}\n")
}
